#!/usr/bin/env ruby
# Copyright 2006-2007 by Starling Software, K.K.
# This is part of QAM from http://www.starling-software.com.
# For license terms, see the LICENSE.QAM file included with this distribution.

require File.expand_path(__FILE__ + "/../../../release/qam")
require 'qam/testsuite'

i = QAM::Install.new
d = i.dirs

i.run_quiet_install(d.mine)

QAM::TestSuite.new(d.mine('lib')).run

include Test::Unit::Assertions
output = IO.popen("irb", 'r+') { |s| s.puts('exit'); s.read }
assert_match(/^release=\//, output)

load(d.mine('test-qu/test-qu.rb'))
