#!/usr/bin/env ruby
# Copyright 2006-2007 by Starling Software, K.K.
# This is part of QAM from http://www.starling-software.com.
# For license terms, see the LICENSE.QAM file included with this distribution.

require File.expand_path(__FILE__ + '/../../release/qam')

install = QAM::Install.new
dirs = install.dirs

dbs = []; libs = []; others = [];
Dir[dirs.mine('**', '*', 'Install')].sort.each { |install_script|
    group = case
	when /^db/.match(File.basename(File.dirname(install_script))): dbs
	when File.directory?(File.dirname(install_script) + '/lib'): libs
	else others
    end
    group << install_script
}

(dbs + libs + others).each { |install_script|
    install.run_quiet_install(install_script)
}
